# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI / CD

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev

permissions:
  id-token: write
  contents: read

jobs:
  test:
    name: Test micro frontend utility
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Installing dependencies
        uses: ./.github/actions/install_deps
        with:
          node-version: ${{ matrix.node-version }}

      - name: Run the tests and generate coverage report
        run: yarn test

  release:
    name: Release new version
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Installing dependencies
        uses: ./.github/actions/install_deps
        with:
          node-version: ${{ matrix.node-version }}
      - name: Release new version
        run: yarn semantic-release
        env:
          GH_TOKEN: ${{ secrets.ACTIONS_DEPLOY_ACCESS_TOKEN }}
          HUSKY: 0
      - name: Build package
        run: yarn build-npm
      - name: Set NPM publish token
        run: npm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Release to NPM
        run: npm publish --access=public

  DeployDevelopment:
    name: Deploy to Development
    if: github.event.ref == 'refs/heads/dev'
    needs: test
    uses: ./.github/workflows/build_and_deploy.yml
    with:
      environment-name: Development
      environment-url: 'https://d2zylh2dyni892.cloudfront.net'
      role-session-name: DeployFrontendSharedModulesDevSession
      aws-region: us-east-1
      identifier: ${{ github.sha }}
      run-import-map-deployer: false
    secrets: inherit

  DeployProduction:
    name: Deploy to Production
    if: github.event.ref == 'refs/heads/master'
    needs: test
    uses: ./.github/workflows/build_and_deploy.yml
    with:
      environment-name: Production
      environment-url: 'https://d1ecqcwx7brud6.cloudfront.net'
      role-session-name: DeployFrontendSharedModulesProdSession
      aws-region: us-east-1
      identifier: ${{ github.sha }}
      run-import-map-deployer: false
    secrets: inherit
